name: i18n (web)
on:
  push:
  pull_request:

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
          yarn workspace web add -D ts-node typescript tsx
      - name: Check Localization
        run: |
          yarn workspace web i18n
